# Generated by Django 3.2 on 2021-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addEmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_a',
            name='ques',
            field=models.CharField(max_length=200),
        ),
    ]
