# Generated by Django 3.2 on 2021-04-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addEmp', '0002_alter_q_a_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='temp1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='temp2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='temp3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
